### ISSUE TITLE
'X' matrix was collinearError in solve.default(crossprod(X, X/vv)) error

### ISSUE THREAD

**Issue by vsmuir** [r-suzuki/pvclust#1]
`results = pvclust(sample_data, method.dist="correlation", method.hclust="average", nboot=1000)`
[sample_data.txt](https://github.com/r-suzuki/pvclust/files/1874092/sample_data.txt)

When attempting to run the above command, I receive the following output/error for the attached sample set: 

Bootstrap (r = 0.5)... Done.
inappropriate distance matrices are omitted in computation: r =  0.5
Bootstrap (r = 0.5)... Done.
inappropriate distance matrices are omitted in computation: r =  0.5
Bootstrap (r = 0.67)... Done.
inappropriate distance matrices are omitted in computation: r =  0.666666666666667
Bootstrap (r = 0.67)... Done.
inappropriate distance matrices are omitted in computation: r =  0.666666666666667
Bootstrap (r = 0.83)... Done.
inappropriate distance matrices are omitted in computation: r =  0.833333333333333
Bootstrap (r = 1.0)... Done.
inappropriate distance matrices are omitted in computation: r =  1
Bootstrap (r = 1.0)... Done.
inappropriate distance matrices are omitted in computation: r =  1
Bootstrap (r = 1.17)... Done.
Bootstrap (r = 1.17)... Done.
inappropriate distance matrices are omitted in computation: r =  1.16666666666667
Bootstrap (r = 1.33)... Done.

'X' matrix was collinearError in solve.default(crossprod(X, X/vv)) : 
  Lapack routine dgesv: system is exactly singular: U[2,2] = 0

I can avoid the error by setting r = 1, but I've successfully run pvclust on a number of other sample sets.  I'd like to be able to use the AU measurements for consistency's sake.

Any suggestions for solving this issue?

**Comment by r-suzuki** [comment]
The relative sample size `r` is set to c(0.5, 0.6, ..., 1.3, 1.4) by default (please see `help(pvclust)`). However your data has only 7 rows so the actual sample sizes duplicate: round(7 * 0.5) = round(7 * 0.6) = 4.

In this case you can use `r = unique(round(seq(.5,1.4,by=.1) * 7)) / 7` to avoid the error.

Please be noticed that this is only a way to avoid the error; the approximation may not be enough good with such a small sample size.

**Comment by vsmuir** [comment]
Thanks a ton for your help!
